### ISSUE TITLE
Clarification for Table 2

### ISSUE THREAD

**Issue by p16i** [meanna/ThaiLMCUT#1]
Hi,

Thank you very much for sharing the paper and the code. May I ask a question regarding Table 2?
![image](https://user-images.githubusercontent.com/1214890/82948976-18a25980-9fa3-11ea-811b-759f110490c8.png)

Is it correct that these metrics are char-level? Would it be possible if you can try to evaluate the results from PyThaiNLP's [benchmark script](https://github.com/PyThaiNLP/pythainlp/blob/dev/bin/word-tokenization-benchmark)? you can use it by using `pip install git+git://github.com/pythainlp/pythainlp#v2.2.0-dev1`

Thank you very much in advance for your clarification!

**Comment by meanna** [comment]
Hi, 
Yes, it is character level evaluation. Sure, I can test it on your benchmark (probably take a while, I'm busy with other things currently). The tokenizer probably won't work well on it though, since both the languages model and the tokenizer were trained only with Thai characters.

**Comment by meanna** [comment]
@heytitle   Could you give the link to the script again?
