### ISSUE TITLE
Can you tell the parameter for LM_2019-10-19_17.05.50?

### ISSUE THREAD

**Issue by wannaphong** [meanna/ThaiLMCUT#3]
Hello. I'm working on testing the thai word Tokenizer  model. Can you tell the parameter for LM_2019-10-19_17.05.50? (Train LM)

Thank you.

**Comment by meanna** [comment]
Hi @wannaphong , 

I guess you mean the command to train the language model that I used in the experiment (It is not LM_2019-10-19_17.05.50 but LM_2019-10-15_23.45.27).

python LanguageModel.py --batchSize 60  --char_dropout_prob 0.01  --char_embedding_size 200  --char_noise_prob 0.1  --hidden_dim 500  --layer_num 3  --learning_rate 0.0001 --sequence_length 100 --epoch 20 --len_lines_per_chunk 1000 --optim "adam" --lstm_num_direction 2 --dataset [dataset name]
